### ISSUE TITLE
Mailings dont display?

### ISSUE THREAD

**Issue by R-Frost** [christianwach/civicrm-wp-mail-sync#1]
Hi Christian.. Im not sure if you want issues here or on the stackexchange site? Let me know

anyway.. I'm a bit new at this Wordpress thing. and not all that good at everything else... but I can mostly find my way around.

I installed your plugin on a test site.. generated a mailing,..checked the mailing was received.  Looked for the mailings page.. but nothing found.  

I checked in the database and I could see the new content type of mailing there and it contained the right information.. but I just cant seem to get it to display.. just get :

Archives
Nothing Found

Am I mising something?

Robert

**Comment by christianwach** [comment]
@R-Frost Thanks for the feedback, Robert - here's better for me than StackExchange.

Unfortunately (for numerous reasons) I haven't had time to develop this plugin since CiviCRM 4.4.n. I started 4.6 compatibility, but the new Angular.js approach didn't lend itself to intercepting Mailing events very easily. This may have changed in the meantime, but I'm sorry to say that I consider this plugin to be mothballed until I have time to devote to it again. PRs would of course be most welcome!

Cheers, Christian

**Comment by R-Frost** [comment]
got it,, thanks
